package:
  format-version: "1.0.0"
  name: "pmci"
  type: "api"
  status: "beta"
  required: false
  version: "3.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.14.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.4.6"
