<#--
/*******************************************************************************
  SPDM Freemarker Template File

  Company:
    Microchip Technology Inc.

  File Name:
   spdm_config.h.ftl

  Summary:
    SPDM Freemarker Template File

  Description:

*******************************************************************************/
-->

/*****************************************************************************
* Copyright (c) 2022 Microchip Technology Inc. and its subsidiaries.
* You may use this software and any derivatives exclusively with
* Microchip products.
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".
* NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
* INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
* AND FITNESS FOR A PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP
* PRODUCTS, COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.
* TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL
* CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF
* FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
* MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE
* OF THESE TERMS.
*****************************************************************************/

/** @file spdm_config.h
 *  SPDM configuration header file
 */
/** @defgroup SPDM Configuration
 */

#ifndef SPDM_CONFIG_H
#define SPDM_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif


#define SPDM_SLOT_CERT_CHAIN01 0x${SPDM_CERT_CHAIN_SLOT_01}
#define SPDM_SLOT_CERT_CHAIN23 0x${SPDM_CERT_CHAIN_SLOT_23}
#define SPDM_SLOT_CERT_CHAIN45 0x${SPDM_CERT_CHAIN_SLOT_45}
#define SPDM_SLOT_CERT_CHAIN67 0x${SPDM_CERT_CHAIN_SLOT_67}

#define SPDM_HEAD_POINTER_0 0x${SPDM_HEAD_POINTER_0}
#define SPDM_HEAD_POINTER_1 0x${SPDM_HEAD_POINTER_1}
#define SPDM_HEAD_POINTER_2 0x${SPDM_HEAD_POINTER_2}
#define SPDM_HEAD_POINTER_3 0x${SPDM_HEAD_POINTER_3}
#define SPDM_HEAD_POINTER_4 0x${SPDM_HEAD_POINTER_4}
#define SPDM_HEAD_POINTER_5 0x${SPDM_HEAD_POINTER_5}
#define SPDM_HEAD_POINTER_6 0x${SPDM_HEAD_POINTER_6}
#define SPDM_HEAD_POINTER_7 0x${SPDM_HEAD_POINTER_7}

#define TAIL_CERTIFICATE0123 0x${TAIL_CERTIFICATE0123}
#define TAIL_CERTIFICATE4567 0x${TAIL_CERTIFICATE4567}
#define TAIL_CERTIFICATE891011 0x${TAIL_CERTIFICATE891011}
#define TAIL_CERTIFICATE12131415 0x${TAIL_CERTIFICATE12131415}
#define TAIL_CERTIFICATE16171819 0x${TAIL_CERTIFICATE16171819}
#define TAIL_CERTIFICATE20212223 0x${TAIL_CERTIFICATE20212223}
#define TAIL_CERTIFICATE24252627 0x${TAIL_CERTIFICATE24252627}
#define TAIL_CERTIFICATE28293031 0x${TAIL_CERTIFICATE28293031}
#define TAIL_CERTIFICATE32333435 0x${TAIL_CERTIFICATE32333435}
#define TAIL_CERTIFICATE36373839 0x${TAIL_CERTIFICATE36373839}
#define TAIL_CERTIFICATE40414243 0x${TAIL_CERTIFICATE40414243}
#define TAIL_CERTIFICATE44454647 0x${TAIL_CERTIFICATE44454647}
#define TAIL_CERTIFICATE48495051 0x${TAIL_CERTIFICATE48495051}
#define TAIL_CERTIFICATE52535455 0x${TAIL_CERTIFICATE52535455}
#define TAIL_CERTIFICATE56575859 0x${TAIL_CERTIFICATE56575859}
#define TAIL_CERTIFICATE60616263 0x${TAIL_CERTIFICATE60616263}

#ifdef __cplusplus
}
#endif

#endif /* SPDM_CONFIG_H */

/**   @}
 */